### ISSUE TITLE
Argument 0 (NSNumber) of RNZoomVideoSdkVideoHelper.rotateMyVideo has unspecified nullability but React requires that all NSNumber arguments are explicitly marked as `nonnull` to ensure compatibility with Android.

### ISSUE THREAD

**Issue by IrynaDoroshenkoDev** [zoom/videosdk-reactnative-quickstart#11]
[@zoom](https://devforum.zoom.us/u/zoom)/react-native-videosdk”: “^1.12.10”,

_Description_
**When I rotate my iPhone and want to rotate a camera on iOS. Only the first time I can see the red alert screen. Note: the video rotated properly on both platforms, Android works fine without any alerts:**

_Error_
Argument 0 (NSNumber) of RNZoomVideoSdkVideoHelper.rotateMyVideo has unspecified nullability but React requires that all NSNumber arguments are explicitly marked as nonnull to ensure compatibility with Android.
RCTLogArgumentError(RCTModuleMethod, unsigned long, objc_object*, char const*)
RCTModuleMethod.mm:67
-[RCTModuleMethod processMethodSignature]
-[RCTModuleMethod invokeWithBridge:module:arguments:]
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_lane_serial_drain
_dispatch_lane_invoke
_dispatch_root_queue_drain_deferred_wlh
_dispatch_workloop_worker_thread
_pthread_wqthread
start_wqthread*

_code_
*const _orientationDidChange = (orientation: OrientationType) => {
try {
if (!zoom || !zoom.videoHelper) return;

  if (
    orientation === OrientationType['LANDSCAPE-LEFT'] ||
    orientation === OrientationType['LANDSCAPE-RIGHT']
  ) {
    zoom.videoHelper.rotateMyVideo(1);
    setVideoOrientation(orientation);
  } else {
    zoom.videoHelper.rotateMyVideo(0);
    setVideoOrientation(OrientationType.PORTRAIT);
  }
  console.log('###Orientation did change : ', orientation);
} catch (error) {
  console.log('###error on rotation', error);
}
};*

_How To Reproduce_
Steps to reproduce the behavior including:
1. try to call zoom.videoHelper.rotateMyVideo(1); on iOS
<img width="232" alt="Screenshot 2024-11-05 at 11 50 38" src="https://github.com/user-attachments/assets/866b0b58-5b5d-4b99-8af2-09e53c4dbce9">

**Comment by EkaanshArora** [comment]
Bug with the SDK, working on a fix. https://devforum.zoom.us/t/argument-0-nsnumber-of-rnzoomvideosdkvideohelper-rotatemyvideo-has-unspecified-nullability-but-react-requires-that-all-nsnumber-arguments-are-explicitly-marked-as-nonnull-to-ensure-compatibility-with-android/120177/2
