### ISSUE TITLE
ZoomVideoSDKError_Wrong_Usages

### ISSUE THREAD

**Issue by ranveerching** [zoom/videosdk-reactnative-quickstart#6]
Getting **ZoomVideoSDKError_Wrong_Usages** after wrapping my newly created app with **ZoomVideoSdkProvider**.

Using following library version(s):
- react: 18.2.0
- react-native: 0.73.4
- @zoom/react-native-videosdk: 1.11.0

**Expected behavior**
Zoom video SDK should be initialised successfully.

**Target Platform (please complete the following information):**
 - Device: Android simulator
 - OS: Android 13

**Describe the bug**
Getting **ZoomVideoSDKError_Wrong_Usages** error after wrapping the app with **ZoomVideoSdkProvider**.

**Comment by EkaanshArora** [comment]
Did you wrap it at the top-level of your app? Can you share the code snippet?

**Comment by ranveerching** [comment]
Yes @EkaanshArora I wrapped the App component(App.tsx) with ZoomVideoSdkProvider. Here is the code snippet:

`import React, {useEffect} from 'react';
import {SafeAreaView, PermissionsAndroid, StyleSheet} from 'react-native';
import {ZoomVideoSdkProvider} from '@zoom/react-native-videosdk';

function App(): React.JSX.Element {
  useEffect(() => {
    async function requestPermissions() {
      try {
        const granted = await PermissionsAndroid.requestMultiple([
          PermissionsAndroid.PERMISSIONS.CAMERA,
          PermissionsAndroid.PERMISSIONS.RECORD_AUDIO,
        ]);
        if (
          granted['android.permission.CAMERA'] ===
            PermissionsAndroid.RESULTS.GRANTED &&
          granted['android.permission.RECORD_AUDIO'] ===
            PermissionsAndroid.RESULTS.GRANTED
        ) {
          console.log('You can use the camera and microphone');
        } else {
          console.log('Permission denied');
        }
      } catch (err) {
        console.warn(err);
      }
    }

    requestPermissions();
  }, []);

  return (
    <ZoomVideoSdkProvider config={{enableLog: true, domain: 'zoom.us'}}>
      <SafeAreaView style={styles.container} />
    </ZoomVideoSdkProvider>
  );
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

export default App;`

**Comment by ranveerching** [comment]
@EkaanshArora Any update on this??

**Comment by singhroshan18** [comment]
hi @ranveerching , is your sdk being initiliazed?

**Comment by syedm121** [comment]
i am stuck on this sdk issue from 3 days . nothing works , Documentation sucks .

**Comment by syedm121** [comment]
@ranveerching  any fix?

**Comment by ombogdan** [comment]
new updates?

**Comment by EkaanshArora** [comment]
@singhroshan18 @syedm121 @ombogdan can you please describe the issue you're facing? Are you getting the `ZoomVideoSDKError_Wrong_Usages` error? In most cases this happens if the `ZoomVideoSdkProvider` is not added, or is being re-rendered.

**Comment by ombogdan** [comment]
<img width="590" alt="image" src="https://github.com/user-attachments/assets/621af8bc-ea3a-45d4-a80d-a4aae26cb8bf">
I added this

**Comment by EkaanshArora** [comment]
@ombogdan move it higher up the component tree please

**Comment by ombogdan** [comment]
i tried that too. but getting the same error. and then just don't join the call. I use an example from the repository

**Comment by EkaanshArora** [comment]
Can you try wrapping the component that is rendering the videocall / where you the `useZoom` hook?

**Comment by ombogdan** [comment]
ok i will try

**Comment by ombogdan** [comment]
<img width="1213" alt="image" src="https://github.com/user-attachments/assets/c5c47ab9-6c1d-499c-9d93-e3fcadf62884">

**Comment by EkaanshArora** [comment]
@ombogdan which navigation library are you using? I can try and spin up an example with it.

**Comment by ombogdan** [comment]
@EkaanshArora react-navigation

**Comment by syedm121** [comment]
sorry i fixed it simply by following the documentation  , imported the template code in my project and thats it its working now

**Comment by ombogdan** [comment]
I just copied the template code instead of my file
+ added ZoomVideoSdkProvider container above navigation. and it doesn't work for me

**Comment by syedm121** [comment]
@ombogdan did u installed it correctly from their official documentation? can u share the snippet with me

**Comment by syedm121** [comment]
![image_2024-07-23_203726499](https://github.com/user-attachments/assets/28ae1904-cc3f-4cbd-ae34-bb2402d29490)

**Comment by syedm121** [comment]
@ombogdan check this.

**Comment by ombogdan** [comment]
I installed  "@zoom/react-native-videosdk": "^1.9.5",
and imported it loke this import {ZoomVideoSdkProvider} from "@zoom/react-native-videosdk";
<img width="680" alt="image" src="https://github.com/user-attachments/assets/ff101d56-b6fc-4991-bd14-609b51d28fdc">
<img width="1091" alt="image" src="https://github.com/user-attachments/assets/9e2eb3ef-af8a-4f5b-9abe-5c47579138f1">

**Comment by syedm121** [comment]
it  should never re render and use the updated version it may cause you problems brother. check my snippet . if sdk is not initialized i dont render it . @ombogdan   {
  "name": "rehnuma",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-native-picker/picker": "^2.7.7",
    "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/native": "^6.1.17",
    "@zoom/react-native-videosdk": "^1.11.0",
    "axios": "^1.7.2",
    "react": "18.2.0",
    "react-native": "0.72.3",
    "react-native-date-picker": "^5.0.4",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-image-picker": "^7.1.2",
    "react-native-modal": "^13.0.1",
    "react-native-multiple-select": "^0.5.12",
    "react-native-pure-jwt": "^3.0.2",
    "react-native-safe-area-context": "^4.10.1",
    "react-native-screens": "^3.31.1",
    "twrnc": "^4.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.9",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.7",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "engines": {
    "node": ">=16"
  }
}

**Comment by syedm121** [comment]
> ![image_2024-07-23_203726499](https://private-user-images.githubusercontent.com/108610670/351393373-28ae1904-cc3f-4cbd-ae34-bb2402d29490.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NDk2NDcsIm5iZiI6MTcyMTc0OTM0NywicGF0aCI6Ii8xMDg2MTA2NzAvMzUxMzkzMzczLTI4YWUxOTA0LWNjM2YtNGNiZC1hZTM0LWJiMjQwMmQyOTQ5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QxNTQyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzRjN2VkNGVmNmI0NjUzNTlmY2YzMjc1MDMzYTA1MGY1ZWY5ZDBjNjY0YjVlZDIyNGFhNWZmN2I1ZGNiYmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d3kjuwSZiqkBO-9W-YnftdJn9y8O5ivTtwb_7gqzMMY)

follow it like this it will work the zoom provider must be above all

**Comment by sana-ishaque** [comment]
Hello. with react native Cli i installed the package yarn add @zoom/react-native-videosdk and added required permissions.
as soon as i wrap the App.js with ZoomVideoSdkProvider it crashes teh app.
<img width="671" alt="image" src="https://github.com/user-attachments/assets/3acb8dff-ba52-4f11-973e-a1dcd1fb11dc">
Also, with npm package, do i really need to install the sdk files and place inside my project ? If yes if you can pls specify the what folder to copied exaclty and placed for android and ios ?

**Comment by sana-ishaque** [comment]
> Hello. with react native Cli i installed the package yarn add @zoom/react-native-videosdk and added required permissions. as soon as i wrap the App.js with ZoomVideoSdkProvider it crashes teh app. <img alt="image" width="671" src="https://private-user-images.githubusercontent.com/49162351/369668060-3acb8dff-ba52-4f11-973e-a1dcd1fb11dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5ODU5NjQsIm5iZiI6MTcyNjk4NTY2NCwicGF0aCI6Ii80OTE2MjM1MS8zNjk2NjgwNjAtM2FjYjhkZmYtYmE1Mi00ZjExLTk3M2UtYTFkY2QxZmIxMWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDA2MTQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMmYzNjQ3M2QyNjBjMjRiNDQzOTUwN2FiMjU4NzcyNDc0ODg0NDI3MDU2MzUzMWQyYzI4M2NjNzBkYWE3YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PJR4_igADlCP-FMv9eUSVo3USuzptkIz0wAyiuqSU5E"> Also, with npm package, do i really need to install the sdk files and place inside my project ? If yes if you can pls specify the what folder to copied exaclty and placed for android and ios ?

as of i now i have just installed the package with yarn and permissions in manifest.

**Comment by sana-ishaque** [comment]
> > Hello. with react native Cli i installed the package yarn add @zoom/react-native-videosdk and added required permissions. as soon as i wrap the App.js with ZoomVideoSdkProvider it crashes teh app. <img alt="image" width="671" src="https://private-user-images.githubusercontent.com/49162351/369668060-3acb8dff-ba52-4f11-973e-a1dcd1fb11dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5ODU5NjQsIm5iZiI6MTcyNjk4NTY2NCwicGF0aCI6Ii80OTE2MjM1MS8zNjk2NjgwNjAtM2FjYjhkZmYtYmE1Mi00ZjExLTk3M2UtYTFkY2QxZmIxMWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDA2MTQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMmYzNjQ3M2QyNjBjMjRiNDQzOTUwN2FiMjU4NzcyNDc0ODg0NDI3MDU2MzUzMWQyYzI4M2NjNzBkYWE3YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PJR4_igADlCP-FMv9eUSVo3USuzptkIz0wAyiuqSU5E"> Also, with npm package, do i really need to install the sdk files and place inside my project ? If yes if you can pls specify the what folder to copied exaclty and placed for android and ios ?
> 
> as of i now i have just installed the package with yarn and permissions in manifest.

Also, sample app with expo is running just fine. Its just i am unable to use this in my existing React Native CLI project.

**Comment by EkaanshArora** [comment]
@sana-ishaque if you're on `v1.12.10` you don't need to install anything manually. Just running `yarn add @zoom/react-native-videosdk` is sufficient. Make sure you run `npx pod-install` if you're running on iOS.

**Comment by sanaishaque** [comment]
@EkaanshArora Thanks it worked :)
