### ISSUE TITLE
Video sdk is not being Initiliazed

### ISSUE THREAD

**Issue by singhroshan18** [zoom/VideoSDK-ReactNative-Quickstart#7]
I have use my own 'ZOOM_APP_KEY' and 'ZOOM_APP_SECRET'.
token is being generated also able to log the but the sdk in not opening on clicking the button 'Join the Session'.
also not getting any error.

**Comment by itsaliraxa** [comment]
Yes, the same issue is with my code, I am able to generate the jwt token but my session is not started and when I run the project with Xcode then I saw the below error and error code

Error 2014 5002
No active call process.

**Comment by EkaanshArora** [comment]
Tracking in #5 
Posting here as well: https://github.com/zoom/VideoSDK-ReactNative-Quickstart/issues/5#issuecomment-2242535058
> From: https://developers.zoom.us/docs/video-sdk/android/error-codes/

Name | Error Code | Description | Suggestion
-- | -- | -- | --
Errors_Session_Invalid_Param | 2014 | Received invalid parameters of join Session. | Please double check the parameters you passed to the method and try again

> Please double check the parameters you passed to the method and try again. Usually this happens when you are using incorrect credentials.
> Did you get the correct Video SDK credentials? Are you using the same sessionName in the JWT and the joinSession call?

**Comment by priya11463** [comment]
how to check for parameters of join session are valid or not
