### ISSUE TITLE
Repo URL wrong in documents

### ISSUE THREAD

**Issue by appieschot** [zoom/VideoSDK-ReactNative-Quickstart#9]
**Describe the bug**
The `readme.md` states a wrong git command as the repo is either renamed or published differently. 

**To Reproduce**
Try to use `git clone https://github.com/zoom/VideoSDK-React-Native.git`. 

**Expected behavior**
Should be `git clone https://github.com/zoom/VideoSDK-ReactNative-Quickstart.git`

**Screenshots**
N/a

**Evironemnt version of: (please complete the following information):**
N/a

**Target Platform (please complete the following information):**
N/a

**Additional context**
N/a

**Comment by EkaanshArora** [comment]
Thanks for flagging, fixed.
